In [96]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


#Bag of Words

In [97]:
import numpy as np
import pandas as pd

In [98]:
df = pd.DataFrame({'text' : ['people watch campusx', 'campusx watch campusx', 'people write comment', 'campusx write comment'], 'output' : [1, 1, 0, 0]})

In [99]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [100]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [101]:
bow = cv.fit_transform(df['text'])

In [102]:
#vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [103]:
print(bow[0].toarray())

[[1 0 1 1 0]]


In [104]:
print(bow[1].toarray())

[[2 0 0 1 0]]


In [105]:
print(bow[2].toarray())

[[0 1 1 0 1]]


In [106]:
print(bow[3].toarray())

[[1 1 0 0 1]]


In [107]:
df1 = pd.read_csv('/content/drive/MyDrive/datasets/IMDB Dataset.csv')


In [108]:
df1.head()


review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [109]:
bow1 = cv.fit_transform(df1['review'])

In [110]:
print(cv.vocabulary_)

{'one': 64116, 'of': 63742, 'the': 90139, 'other': 64761, 'reviewers': 75495, 'has': 40736, 'mentioned': 57544, 'that': 90116, 'after': 2970, 'watching': 98202, 'just': 48461, 'oz': 65454, 'episode': 30108, 'you': 101071, 'll': 53210, 'be': 8758, 'hooked': 42841, 'they': 90326, 'are': 5707, 'right': 75899, 'as': 6166, 'this': 90434, 'is': 46756, 'exactly': 30969, 'what': 98823, 'happened': 40436, 'with': 99716, 'me': 56968, 'br': 12040, 'first': 33519, 'thing': 90378, 'struck': 86576, 'about': 1865, 'was': 98125, 'its': 46945, 'brutality': 12973, 'and': 4541, 'unflinching': 94597, 'scenes': 78727, 'violence': 97119, 'which': 98927, 'set': 80293, 'in': 44754, 'from': 35401, 'word': 100070, 'go': 37788, 'trust': 92940, 'not': 62902, 'show': 81418, 'for': 34436, 'faint': 31911, 'hearted': 41162, 'or': 64402, 'timid': 90957, 'pulls': 71576, 'no': 62536, 'punches': 71623, 'regards': 74092, 'to': 91195, 'drugs': 27438, 'sex': 80389, 'hardcore': 40498, 'classic': 17533, 'use': 95794, 'it': 46

In [111]:
print(bow1[6].toarray())

[[0 0 0 ... 0 0 0]]


#Ngrams

In [112]:
df = pd.DataFrame({'text' : ['people watch campusx', 'campusx watch campusx', 'people write comment', 'campusx write comment'], 'output' : [1, 1, 0, 0]})

In [113]:
cv1 = CountVectorizer(ngram_range = (2, 2))

In [114]:
ngrams = cv1.fit_transform(df['text'])

In [115]:
print(cv1.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [116]:
cv2 = CountVectorizer(ngram_range = (1, 2))

In [117]:
ngrams1 = cv2.fit_transform(df['text'])

In [118]:
print(cv2.vocabulary_)

{'people': 4, 'watch': 7, 'campusx': 0, 'people watch': 5, 'watch campusx': 8, 'campusx watch': 1, 'write': 9, 'comment': 3, 'people write': 6, 'write comment': 10, 'campusx write': 2}


In [119]:
cv3 = CountVectorizer(ngram_range = (1, 3))

In [120]:
ngrams2 = cv3.fit_transform(df['text'])

In [121]:
print(cv3.vocabulary_)

{'people': 6, 'watch': 11, 'campusx': 0, 'people watch': 7, 'watch campusx': 12, 'people watch campusx': 8, 'campusx watch': 1, 'campusx watch campusx': 2, 'write': 13, 'comment': 5, 'people write': 9, 'write comment': 14, 'people write comment': 10, 'campusx write': 3, 'campusx write comment': 4}


In [122]:
print(len(cv3.vocabulary_))


15


In [123]:
cv4 = CountVectorizer(ngram_range = (2, 2))

In [124]:
ngrams4 = cv4.fit_transform(df1['review'])

In [125]:
print(cv4.vocabulary_)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [126]:
print(len(cv4.vocabulary_))

2364669


#Tf-Idf

In [127]:
df = pd.DataFrame({'text' : ['people watch campusx', 'campusx watch campusx', 'people write comment', 'campusx write comment'], 'output' : [1, 1, 0, 0]})

In [128]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [129]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [130]:
tfidf = TfidfVectorizer()

In [131]:
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [132]:
print(tfidf.idf_)

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]


In [133]:
print(tfidf.get_feature_names_out())

['campusx' 'comment' 'people' 'watch' 'write']


In [134]:
#tfidf.fit_transform(df1['review']).toarray()

In [135]:
tfidf.fit_transform(df1['review'])

<50000x101870 sparse matrix of type '<class 'numpy.float64'>'
	with 6820727 stored elements in Compressed Sparse Row format>

In [136]:
tfidf.get_feature_names_out()


array(['00', '000', '00000000000', ..., 'żmijewski', 'יגאל', 'כרמון'],
      dtype=object)