In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [2]:
import numpy as np
import pandas as pd

In [3]:
temp_df = pd.read_csv('/content/drive/MyDrive/datasets/IMDB Dataset.csv')

In [4]:
df = temp_df.iloc[:10000]

In [5]:
df.head(4)

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative

In [6]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [7]:
df['sentiment'].value_counts()

positive    5028
negative    4972
Name: sentiment, dtype: int64

In [8]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [9]:
df.duplicated().sum()

17

In [10]:
df.drop_duplicates(inplace = True)

<ipython-input-10-9ce7144259af>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace = True)


In [11]:
df.duplicated().sum()

0

In [12]:
import re
def remove_tags(raw_text) :
  cleaned_text = re.sub(re.compile('<.*?/>'), '', raw_text)
  return cleaned_text

In [13]:
df['review'] = df['review'].apply(remove_tags)

<ipython-input-13-00e93c2a3043>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_tags)


In [14]:
df

review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. The filming tec...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[9983 rows x 2 columns]

In [15]:
df['review'] = df['review'].apply(lambda x : x.lower())

<ipython-input-15-4bf0c210ee59>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x : x.lower())


In [16]:
!pip install nltk


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [17]:
!pip install nltk corpora


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [18]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [19]:
from nltk.corpus import stopwords


In [20]:
st = stopwords.words('english')


In [21]:
def remove_stopwords(text) :
  new_text = []
  for word in text.split() :
    if word in st :
      new_text.append(' ')
    else :
      new_text.append(word)

  x = new_text[:]
  new_text.clear()
  return " ".join(x)

In [22]:
df["review"] = df["review"].apply(remove_stopwords)


<ipython-input-22-1a46ae7dd906>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["review"] = df["review"].apply(remove_stopwords)


In [23]:
df['review'][0]



"one       reviewers   mentioned     watching   1 oz episode     hooked.     right,       exactly   happened   me.the first thing   struck     oz     brutality   unflinching scenes   violence,   set   right     word go. trust me,         show     faint hearted   timid.   show pulls   punches   regards   drugs, sex   violence.     hardcore,     classic use     word.it   called oz         nickname given     oswald maximum security state penitentary.   focuses mainly   emerald city,   experimental section     prison       cells   glass fronts   face inwards,   privacy     high     agenda. em city   home   many..aryans, muslims, gangstas, latinos, christians, italians, irish   more....so scuffles, death stares, dodgy dealings   shady agreements   never far away.i would say   main appeal     show   due     fact     goes     shows   dare. forget pretty pictures painted   mainstream audiences, forget charm, forget romance...oz   mess around.   first episode   ever saw struck       nasty     s

In [24]:
X = df.iloc[:, 0:1]
Y = df['sentiment']

In [25]:
X

review
0     one       reviewers   mentioned     watching  ...
1       wonderful little production.   filming techn...
2       thought       wonderful way   spend time    ...
3     basically there's   family     little boy (jak...
4     petter mattei's "love     time   money"     vi...
...                                                 ...
9995  fun, entertaining movie   wwii german spy (jul...
9996  give     break.     anyone say         "good h...
9997    movie     bad movie.     watching   endless ...
9998        movie     probably made   entertain   mi...
9999  smashing film   film-making. shows   intense  ...

[9983 rows x 1 columns]

In [26]:
Y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...   
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

In [27]:
from sklearn.preprocessing import LabelEncoder

In [28]:
encoder = LabelEncoder()

In [29]:
Y = encoder.fit_transform(Y)

In [30]:
Y

array([1, 1, 1, ..., 0, 0, 1])

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)

In [33]:
X_train.shape

(7986, 1)

In [34]:
from sklearn.feature_extraction.text import CountVectorizer


In [35]:
cv = CountVectorizer()

In [36]:
X_train_bow = cv.fit_transform(X_train['review']).toarray()

In [37]:
X_test_bow = cv.transform(X_test['review']).toarray()

In [38]:
X_train_bow.shape

(7986, 48273)

In [39]:
X_test_bow.shape

(1997, 48273)

#Naive Bayes

In [40]:
from sklearn.naive_bayes import GaussianNB

In [41]:
gnb = GaussianNB()
gnb.fit(X_train_bow, Y_train)

GaussianNB()

In [42]:
y_pred = gnb.predict(X_test_bow)

In [43]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [44]:
accuracy_score(Y_test, y_pred)

0.6329494241362043

In [45]:
confusion_matrix(Y_test, y_pred)

array([[717, 235],
       [498, 547]])

#Random Forest

In [46]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()




In [47]:
rf.fit(X_train_bow,Y_train)
y_pred = rf.predict(X_test_bow)

In [48]:
accuracy_score(Y_test, y_pred)

0.8497746619929895

In [49]:
cv = CountVectorizer(max_features=3000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,Y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(Y_test,y_pred)

0.8327491236855283

#Using N Grams

In [50]:
cv = CountVectorizer(ngram_range=(1,2),max_features=5000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,Y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(Y_test,y_pred)

0.8387581372058087

#Using TF IDF

In [51]:
from sklearn.feature_extraction.text import TfidfVectorizer


In [52]:
tfidf = TfidfVectorizer()


In [53]:
X_train_tfidf = tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf = tfidf.transform(X_test['review'])

In [54]:
rf = RandomForestClassifier()

rf.fit(X_train_tfidf,Y_train)
y_pred = rf.predict(X_test_tfidf)

accuracy_score(Y_test,y_pred)

0.8432648973460191

#word to vec

In [55]:
import gensim

In [56]:
from nltk import sent_tokenize

In [57]:
from gensim.utils import simple_preprocess

In [58]:
import nltk

In [59]:
 nltk.download('punkt')
  

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [60]:
story = []
for doc in df['review'] :
  raw_sent = sent_tokenize(doc)
  for sent in raw_sent :
    story.append(simple_preprocess(sent))


In [61]:
model = gensim.models.Word2Vec(
    window = 10,
    min_count = 2
)

In [62]:
model.build_vocab(story)

In [63]:
model.train(story, total_examples = model.corpus_count, epochs = model.epochs)

(5872140, 6208690)

In [64]:
len(model.wv.index_to_key)

31841

In [65]:
def document_vector(doc):
    # remove out-of-vocabulary words
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc], axis=0)

In [66]:
from tqdm import tqdm

In [67]:
X = []
for doc in tqdm(df['review'].values) :
  X.append(document_vector(doc))

100%|██████████| 9983/9983 [07:02<00:00, 23.65it/s]


In [68]:
document_vector(df['review'].values[0])


array([-0.23100516,  0.39825028,  0.23501958,  0.21580689,  0.13754   ,
       -0.5631982 ,  0.29091856,  0.7337352 , -0.32122803, -0.32400066,
       -0.14194274, -0.47218493, -0.02479913,  0.06120534,  0.06911922,
       -0.18466751, -0.10509332, -0.42485365, -0.06301482, -0.7681028 ,
        0.16671433,  0.10352556,  0.2597172 , -0.2547923 , -0.22224295,
       -0.10152839, -0.32736784,  0.06331186, -0.27685225,  0.0353006 ,
        0.24282368,  0.06608055,  0.1977128 , -0.24252416, -0.23914316,
        0.4351448 ,  0.0423985 , -0.3324252 , -0.12045766, -0.7047818 ,
        0.0943569 , -0.22467314, -0.08349792,  0.03111964,  0.3563754 ,
       -0.21237737, -0.29229715, -0.04311095, -0.01123868,  0.36567527,
        0.14048961, -0.3896213 , -0.28306752, -0.13159776,  0.02368335,
        0.22254655,  0.38830003,  0.20439671, -0.29973006,  0.16768216,
        0.04475673,  0.12480936, -0.05069293, -0.07025497, -0.434155  ,
        0.28259614,  0.09576271,  0.3132623 , -0.40166646,  0.28

In [69]:
X = np.array(X)

In [70]:
X[0]



array([-0.23100516,  0.39825028,  0.23501958,  0.21580689,  0.13754   ,
       -0.5631982 ,  0.29091856,  0.7337352 , -0.32122803, -0.32400066,
       -0.14194274, -0.47218493, -0.02479913,  0.06120534,  0.06911922,
       -0.18466751, -0.10509332, -0.42485365, -0.06301482, -0.7681028 ,
        0.16671433,  0.10352556,  0.2597172 , -0.2547923 , -0.22224295,
       -0.10152839, -0.32736784,  0.06331186, -0.27685225,  0.0353006 ,
        0.24282368,  0.06608055,  0.1977128 , -0.24252416, -0.23914316,
        0.4351448 ,  0.0423985 , -0.3324252 , -0.12045766, -0.7047818 ,
        0.0943569 , -0.22467314, -0.08349792,  0.03111964,  0.3563754 ,
       -0.21237737, -0.29229715, -0.04311095, -0.01123868,  0.36567527,
        0.14048961, -0.3896213 , -0.28306752, -0.13159776,  0.02368335,
        0.22254655,  0.38830003,  0.20439671, -0.29973006,  0.16768216,
        0.04475673,  0.12480936, -0.05069293, -0.07025497, -0.434155  ,
        0.28259614,  0.09576271,  0.3132623 , -0.40166646,  0.28

In [73]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

y = encoder.fit_transform(df['sentiment'])

In [74]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [75]:
rf = RandomForestClassifier()


In [76]:
rf.fit(X_train, y_train)

RandomForestClassifier()

In [77]:
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7766649974962444